### ISSUE TITLE
report delle presenze

### ISSUE THREAD

**Issue by ddiamanti-krea** [kreasistemi/KreaEAR#10]
mettere in linea per iniziare a fare dei controlli e verificarne le funzionalità.

**Comment by francescoKREA** [comment]
Volevamo presentarvi qualcosa entro oggi ma purtroppo non ci siamo riusciti.
Comunque vi mando intanto un paio di screen del lavoro che stiamo facendo in locale.
Stiamo lavorando in particolar modo sul back-end, dove le operazioni sono quasi concluse, e abbiamo iniziato anche la parte di front-end che è quella che vi riguarda maggiormente.

Questo è come verrà lato back-end la parte di report
![report](https://github.com/user-attachments/assets/e54342ff-d628-4a06-861b-cc57e21ae69b)

Qui lato front-end come avrete l'elenco delle timbrature caricate,
![report1](https://github.com/user-attachments/assets/c4fc8ff3-3610-4352-b43d-0a717d9e9efa)
