### ISSUE TITLE
Attività Didattiche

### ISSUE THREAD

**Issue by ddiamanti-krea** [kreasistemi/KreaEAR#13]
Per le attività didattiche abbiamo necessità di poter specificare anche le ore totali dell’attività didattica in modo da poter poter avere nel report la % di frequenza rispetto al totale delle ore dell'attività. 
Per il sostegno erano già state fornite lo scorso anno? 
Se sì per ora va bene così ma, in vista dell’utilizzo del sw anche per altri corsi di studio, ci sarà la necessità (anche successivamente) di generalizzare quest'aspetto.

**Comment by MocavUNIMC** [comment]
RIUNIONE DEL 03/09/2024
Francesco mi conferma che già tengono conto di totale ore erogate per una certa attività didattica e che il report legge il tipo di attività dalla tabella delle attività e non da aule.unimc.it quindi si può chiudere anche questo
