### ISSUE TITLE
Segnalazione errore in inserimento dei dati di una maschera

### ISSUE THREAD

**Issue by ddiamanti-krea** [kreasistemi/KreaEAR#14]
funzioni INSERIMENTO NUOVO STUDENTE e ASSOCIAZIONE LEZIONI A ORARI CARICATI: vado ad inserire i dati e quando clicco su Invia per salvare ho il seguente messaggio di errore “Codice di verifica non valido!”

![image](https://github.com/user-attachments/assets/a6d2824d-97ca-4351-915b-e00bcbe693d6)

**Comment by MocavUNIMC** [comment]
ok si può chiudere
