### ISSUE TITLE
Report, calcolo % frequenza su ogni singola lezione tenendo conto della tolleranza 

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#18]
Noi stabiliremo una tolleranza su ogni singola lezione (ad esempio: a fronte di una lezione di 5 ore per noi risulta presente al 100% se ha frequentato almeno 4.5 ore). 
Quindi il 100% potrà essere impostato anche quando la timbratura rispetta questa tolleranza. Quindi nella colonna dove avevo chiesto di estrarre la % di presenza per ogni attività didattica non avremo una formula matematica ma una formula del genere:
-	Se la timbratura sulla singola lezione rispetta la tolleranza -> 100%
-	Se la timbratura non rispetta la tolleranza -> calcolo % delle ore frequentate rispetto alle ore erogate su quella lezione
-	Media aritmetica di tutte queste % sul totale delle lezioni

**Esempio:**
**ATTIVITA' DIDATTICA X - LEZIONE 1:**    frequentate 4.5 ore su 5 -> 100% frequenza
**ATTIVITA' DIDATTICA X - LEZIONE 2:**    2.5 ore frequentate su 5 -> 50% frequenza

**---> RISPETTO A QUESTA ATTIVITA’ DIDATTICA LA FREQUENZA E’ (100+50) / 2 = 75%**

**Comment by MocavUNIMC** [comment]
Le colleghe mi hanno appena detto che l'impostazione di questo calcolo potrebbe subire aggiornamenti in base alle decisioni che potrebbe prendere la direttrice del corso. Vi terrò aggiornati

**Comment by francescoKREA** [comment]
Effettuate le modifiche al calcolo delle tolleranze secondo quanto indicato. File progetto aggiornati il 03 dicembre
