### ISSUE TITLE
Report di hikcentral non leggono timbrature massive

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#20]
**PRIORITA' ALTA**
Ho inserito delle timbrature massive per la SECONDARIA II GRADO GRUPPO 1 e anche GRUPPO 2 per il13/09 dalle ore 14.30 alle ore 18.30.
Ho ricalcolato l'intera giornata del 13/09 per tutti gli studenti.
L'ho fatto anche per INFANZIA_PRIMARIA e I_GRADO e funziona tutto (compresi i report).

**PROBLEMA:** Per gli studenti della SECONDARIA II GRADO GRUPPO 1 e GRUPPO 2 invece, se vado nella funzione DATI E GESTIONE - RECORD NON ELABORATI oppure DATI E GESTIONE - HANDLE vedo correttamente le timbrature (come avviene per INFANZIA_PRIMARIA e I_GRADO). Invese se vado nei report e nella funzione DATI E GESTIONE - RISULTATI DELLE PRESENZE è come se le timbrature non fossero state inserite, non le conteggia proprio.

Ho fatto diverse prove eliminando e reinserendo le timbrature ma il risultato è sempre lo stesso.
Le timbrature massive sono state inserite dalla funzione RECORD NON ELABORATI - GESTIONE DEI RECORD, ho selezionato tutti gli studenti di un gruppo ed ho inserito contemporaneamente sia il check-in che il check-out

**Comment by MocavUNIMC** [comment]
aggiungo che, se nella funzione DATI E GESTIONE - HANDLE inserendo nel campo filtro nome la stringa GIACOM e impostando la data 13/09/2024, si vede che escono fuori delle timbrature di diversi ordini di scuola. Quelle di INFANZIA_PRIMARIA e I_GRADO funzionano, quelle del II grado no; a colpo d'occhio sembrano identiche

**Comment by francescoKREA** [comment]
Ho controllato sembrava non si fossero correttamente aggiornati i programmi dei turni dei 2 gruppi, li ho riapplicati e ora dovrebbero comparire correttamente anche negli altri menù e nei report
