### ISSUE TITLE
Report giornaliero non estare timbrature corrette

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#21]
Ho eseguito il report giornaliero sul 14 settembre e tutti i gruppi.
Per i seguenti studenti, che hanno partecipato solo alla lezione del pomeriggio, ci sono sia timbratura di entrata che timbratura di uscita ma il report mostra solo quella di entrata, anche se poi il calcolo delle ore è corretto.

![immagine](https://github.com/user-attachments/assets/e4ba487c-7a53-4c39-9778-070b5cc2006f)

Ho controllato che lo stesso problema si verifica anche per FRANCESCO SENESI (tutti gli altri gli ho cambiato cognome per indicare che sono percorsi abbreviati ma non dipende da questo perché SENESI è un caso diverso).

Il calcolo delle ore sembra comunque corretto ma è importante che funzioni bene anche l'estrazione delle timbrature altrimenti le tutor avrebbero dubbi sull'affidabilità del report.

**Comment by francescoKREA** [comment]
Qualsiasi tipo di modifica sull'elenco degli studenti in questa fase ci deve essere comunica, perché potrebbero sorgere problemi,
In ogni caso ho provato e nel report giornaliero compaiono anche le uscite. ho effettuato un test anche con il vostro utente per escludere che potessero esserci incongruenze col nostro utente.

**Comment by MocavUNIMC** [comment]
Si Francesco, te lo comunicheremo ma non credo che il sw faccia agganci per stringa del cognome (sennò sarebbe grave).
Abbiamo bisogno di dare in mano alle tutor qualche strumento per analizzare le presenze e ci stiamo arrangiando.
Comunque ne ho trovati altri

![immagine](https://github.com/user-attachments/assets/8f1d0c10-35be-4d6f-90f6-016f9dbdf629)

Io in questo report non vedo tutte le timbrature. Mi sembra che il problema ci sia,
Sto eseguendo report uno dietro l'altro.
Invece da Risultati delle presenze e Record non elaborati si vedono.
