### ISSUE TITLE
Report danno problemi con 2 timbrature nello stesso minuto

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#22]
Abbiamo parecchi casi di studenti che hanno fatto 2 timbrature nello stesso minuto (una di uscita e l'altra di entrata a distanza di pochi secondi).
Questi situazioni creano problemi ai report perché non vengono estratte tutte le timbrature ma solo alcune.
Riporto sotto qualche esempio e il report usato è quello GIORNALIERO.

![immagine](https://github.com/user-attachments/assets/354ee737-ca6c-4a16-9aaf-5f606955c708)
![immagine](https://github.com/user-attachments/assets/eb2a644c-e659-4b8e-9af0-0f46aaa113fd)
![immagine](https://github.com/user-attachments/assets/aa8d805d-c96b-4bf7-b261-096dc5bce586)
![immagine](https://github.com/user-attachments/assets/ee6817d1-632f-4392-837e-dbe49f16e810)

So che riguarda il sw dell'altra ditta. Non so se si può sollevare il problema per farlo risolvere.

**Comment by matteomercuri77** [comment]
OK abbiamo trovato il modo di correggere queste anomalie, tramite la funzionalità "**GESTIONE ECCEZIONI**".

Chiudo questo ticket. Lascio aperto l'altro affinchè tali anomalie possano non verificarsi proprio, nel software HikCentral.
