### ISSUE TITLE
Orari caricati: inserire dei filtri sopra alla lista

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#23]
**PRIORITA' ALTA**
Nella funzione ORARI CARICATI abbiamo bisogno di avere dei filtri sopra alla lista.
Sarebbero necessari almeno i seguenti filtri:
- da data a data
- attività didattica associata (codificata in tendina)

**Comment by MocavUNIMC** [comment]
Bene per il filtro sulla descrizione attività.
Il filtro sulla data di inizio lezione invece non funziona: se imposto data inizio lezione il 20 settembre mi estrae anche il 14 settembre
![immagine](https://github.com/user-attachments/assets/1bb9fd1f-8032-4484-81d5-3a541eefda39)

**Comment by francescoKREA** [comment]
sistemata la ricerca per data di inizio lezione, e aggiunto la selezione dell'attività, codificata in tendina, come richiesto
