### ISSUE TITLE
Correzione timbrature di studenti che hanno timbrato ENTRATA/USCITA nello stesso minuto

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#24]
Avrei necessità di correggere le timbrature della studentessa MARTINA SFREDDA e anche altri (ad esempio anche MIRIANA ERCOLI) che hanno timbrato Entrata / Uscita nello stesso minuto.
In questa situazione i report non funzionano correttamente.
**_Abbiamo una funzione di manutenzione che ci permette di essere autonomi?_**

Fammi sapere altrimenti dovremmo inviare a voi tutte queste manutenzioni e mi sembra scomodo.

**Comment by francescoKREA** [comment]
Non è possibile modificare le timbrature effettuate tramite terminale.
L'esclusione per le timbrature dell'utente effettuate nel range di 1 minuto è un parametro che non è possibile rimuovere.
L'unica soluzione è l'aggiunta della timbratura necessaria prima del minuto nell'hikcentral oppure l'esclusione delle timbratura errata potrà essere fatta nel nostro software dopo che è stato caricato il file esportato dall'hikcentral, avendo già previsto la casistica in oggetto.
