### ISSUE TITLE
Hikcentral - non vengono estratte timbrature SEC_II_GRADO_GRUPPO 1

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#25]
**PRIORITA' ALTA PERCHE' ALTRIMENTI NON FUNZIONANO I REPORT**
Sto monitorando gli accessi alla lezione di oggi pomeriggio 27/09 e visto che siamo quasi alla fine sono andata in DATI E GESTIONE - RISULTATI DELLE PRESENZE e poi **ricalcola**.
Poi ho estratto tutti per avere una situazione degli assenti in questo momento e vedo che non mi estrae nessuno della secondaria II grado gruppo 1 ma le timbrature ci sono.

L'ho fatto più volte ma il risultato è sempre lo stesso.
Una cosa simile era successa scorsa settimana quando ho inserito delle timbrature massive che non mi leggeva.

Si può ricontrollare questo gruppo per vedere se ha qualcosa di diverso rispetto agli altri?

**Comment by francescoKREA** [comment]
Aveva perso la programmazione per il giorno, ho sistemato e ora sono ok
