### ISSUE TITLE
Tolleranze nel report delle presenze

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#27]
Gentilissimi,
allego il file delle specifiche della tolleranza da applicare nel calcolo della % di presenza a lezione.
Sono le stesse specifiche che vi ho anticipato oggi durante la call.
Per qualsiasi dubbio scrivetemi pure.
[13_tolleranze_da_applicare_al_report_KREASISTEMI.docx](https://github.com/user-attachments/files/17342911/13_tolleranze_da_applicare_al_report_KREASISTEMI.docx)

**Comment by francescoKREA** [comment]
Buonasera, 
abbiamo provveduto ad aggiornare il software per l'analisi delle presenze. Sono state aggiunte le modifiche richieste per il conteggio e le tolleranze.
Rimangono problemi sulla velocità dei calcoli: al caricamento del gruppo, occorrono 60 secondi sia per la visualizzazione dei risultati, che per l'export.
Non è ancora presente la variante per le attività di recupero.

Ci sono attività didattiche inserite più volte, in particolare per SEC_II_GRADO_gruppo1, vi chiediamo la cortesia di controllare e correggere eliminando le attività replicate.
