### ISSUE TITLE
Report non estrae ancora i dati

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#29]
Purtroppo stamattina il sw non estrae ancora nulla: parlo della funzione Report
![thumbnail_image](https://github.com/user-attachments/assets/1314e1ed-0792-4839-afae-58b329fee783)

Non avete ancora caricato i dati?
ce li potresti caricare in giornata così iniziamo a fare i controlli?

Ricordiamo che vanno tolti gli studenti dello scorso anno.
Secondo me sarebbe preferibile non toglierli proprio ma inserire un altro attributo sulla tabella degli studenti per l'anno accademico così da filtrare gli studenti dell'a.a. di interesse (mi sembra più giusto)

**Comment by francescoKREA** [comment]
I dati delle presenze presi dall'hikcentral sono stati importati nel nostro software, e sono stati spostati in un'altra tabella non visibile gli studenti dello scorso anno
