### ISSUE TITLE
funzione REPORT - c'è un blank davanti al cognome

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#31]
**ERRORE, PRIORITA’ ALTA:** 
nel campo cognome il primo carattere è sempre un blank; la priorità è alta perché non essendo estratto l’id dello studente in Kreasistemi mi serve per fare delle formule di controllo in Excel su nome e cognome

Rilevato che lo stesso problema c'è anche per il campo nome

**Comment by francescoKREA** [comment]
Tolto lo spazio prima del cognome e del nome nel report
