### ISSUE TITLE
funzione REPORT - non vengono estratti tutti i dati

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#32]
**ERRORE, PRIORITA’ ALTA:** 
Estraggo i dati del 4/10 senza nessun altro filtro sia nel report Kreasistemi che nel Registro presenze di hik central; 
in hikcentral mi estrae 650 studenti compresi gli assenti (giusto), nel report Kreasistemi mi estrae 466 studenti (me li deve estrarre tutti 650 compresi gli assenti del giorno, per loro le ore saranno 0); mancano 1 studente per il gruppo infanzia_primaria, 7 studenti per la secondaria I grado, manca tutta la secondaria di II grado gruppo 1, mancano 17 studenti della secondaria di II grado gruppo 2

**Comment by MocavUNIMC** [comment]
INFANZIA_PRIMARIA ok, si tratta di COVELLA che poi si è ritirata quindi non ci interessa

**Comment by MocavUNIMC** [comment]
per la secondaria di I grado si tratta dei 7 percorsi abbreviati per cui abbiamo inserito la stringa "abbreviato" sul cognome 
![immagine](https://github.com/user-attachments/assets/2731d053-fab6-4777-a588-8323ae9d6192)

**Comment by MocavUNIMC** [comment]
i 17 non estratti della secondaria II grado - gruppo 2 sono i seguenti 
![immagine](https://github.com/user-attachments/assets/1e4938a8-bc62-4d6c-b885-4ccf5ad806f8)

**Comment by MocavUNIMC** [comment]
**PRIORITA' ALTA**
l'aspetto più importante è che manca ancora tutta la secondaria di II grado gruppo 1

**Comment by francescoKREA** [comment]
Ci sono 643 corsisti perché era stato creato questo utente
![image](https://github.com/user-attachments/assets/83be9e11-f0a9-48c7-bf4d-f54884de80f1)
devo eliminarlo?

**Comment by francescoKREA** [comment]
Utente eliminato come da richiesta

**Comment by francescoKREA** [comment]
Funzionalità di report corretta con aggiornamento file del 03 dicembre
