### ISSUE TITLE
funzione REPORT - serve una colonna per individuare i percorsi abbreviati

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#34]
**MIGLIORIA, PRIORITA’ ALTA (ticket #34):** 
nel report ci serve la colonna che ci indica se si tratta di percorso abbreviato altrimenti non si riesce ad analizzare correttamente questi studenti che devono frequentare solo laboratori e tirocini indiretti

Credo che per identificare i percorsi abbreviati possiamo usare il campo Ridotto settandolo a SI
![immagine](https://github.com/user-attachments/assets/e1221a3d-ca25-4e94-9b1d-c1e47078ad7f)

**Oppure il campo serve ad altro?**

**Comment by francescoKREA** [comment]
aggiunto il campo Ridotto nei report
