### ISSUE TITLE
funzione REPORT, ci mette molto ad entrare come se stesse estraendo i dati

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#35]
**MIGLIORIA, PRIORITA’ ALTA:** 
All’entrata della funzione ci mette quasi un minuto come se stesse estraendo qualcosa ma poi la lista è vuota; 
comunque non dovrebbe estrarre tutti i dati subito ma entrare con la lista vuota e aspettare che settiamo i filtri; fra qualche settimana avremo più di 100 mila timbrature e non serve estrarle tutte insieme; sicuramente prima potrebbe essere comodo applicare almeno il filtro sul gruppo

**Comment by francescoKREA** [comment]
Aggiunto l'obbligatorietà del filtro gruppo.
