### ISSUE TITLE
funzione REPORT, non estrae tutte le righe delle attività didattiche frequentate

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#36]
**ERRORE, PRIORITA' ALTA:**
il numero di righe estratte per ogni studente deve essere fisso (stesso numero delle attività didattiche del corso) anche se per alcune attività didattiche non sono mai state erogate lezioni; l’errore si vede bene estraendo i dati di uno studente solo; ad esempio per ADA MICHELA MASTROLORITO viene estratta una riga sola mentre lei avrà partecipato di sicuro a diverse lezioni
![immagine](https://github.com/user-attachments/assets/a016b6f2-166b-4ebe-a7a3-16f0b3a067a9)

Infatti, solo nel mese di settembre ha partecipato a 5 lezioni (lo vedo dal report mensile di hikcentral) ed erano relative alle materie indicate al seguente link
https://sfbct.unimc.it/it/didattica/corso-specializzazione-sostegno/corso-di-specializzazione-per-il-sostegno-a.a.-2023-2024/CalendarioSEC.IIGRGRUPPO2_settembre_ottobre.pdf

Le lezioni sono correttamente associate all’attività didattica quindi dovrebbe estrarre una riga per ogni attività didattica per cui è stata erogata almeno una lezione.

**Comment by MocavUNIMC** [comment]
ad analizzare altri casi sembra solo un problema di raggruppamento dei record estratti perché sembra raggruppare solo per studente invece dovrebbe raggruppare per studente, attività didattica e forse si risolve

**Comment by MocavUNIMC** [comment]
Mi sembra che il report funzioni meglio ma non mi estrae gli assenti.
Ad esempio se filtro per il 4/10, gruppo SECONDARIA di I GRADO non mi estrae i 7 assenti 

GIADA   PIATTONI-abbreviato | 1311
MARGHERITA   MENGONI-abbreviato | 812
OTILIA   ENACHE-abbreviato | 849
BEATRICE   MASSETANI-abbreviato | 850
LORENZO   ANTOLINI-abbreviato | 855
ALESSIO   GATTAFONI-abbreviato | 878
ELISA   IOMMI-abbreviato | 930

E' utile per avere una visione d'insieme di tutto il gruppo.

**Comment by francescoKREA** [comment]
lista risultati corretta con aggiornamento file progetto aggiornati il 03 dicembre
