### ISSUE TITLE
funzione REPORT, orari entrata a lezione timbrati un'ora prima dell'inizio - RIFLESSIONE

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#37]
Molti studenti timbrano l'entrata molto prima del'inizio della lezione; questo comporta che superano le 5 ore di frequenza anche se in realtà la permanenza in aula durante la lezione non è così alta (potrebbe anche accadere che timbri l'entrata alle 13:00 e esca alle 17:30 quindi in anticipo e la sua presenza risulterebbe 4,5 ore).
Riporto qualche esempio
![immagine](https://github.com/user-attachments/assets/f29fc3f2-3f2a-4dca-8429-f1a30009786b)

Dobbiamo testare che tutti i ragionamenti stabiliti per le tolleranze funzionino bene in questi casi perché la % di permanenza effettiva in aula per queste lezioni non deve risultare 100% ma più bassa

**Comment by francescoKREA** [comment]
Effettuate correzione secondo quanto richiesto file aggiornati il 03 dicembre
