### ISSUE TITLE
funzione REPORT, non estrae assenti

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#38]
**PRIORITA' MEDIA**
Non mi estrae gli assenti.
Ad esempio se filtro per il 4/10, gruppo SECONDARIA di I GRADO non mi estrae i 7 assenti

- GIADA PIATTONI-abbreviato | 1311
- MARGHERITA MENGONI-abbreviato | 812
- OTILIA ENACHE-abbreviato | 849
- BEATRICE MASSETANI-abbreviato | 850
- LORENZO ANTOLINI-abbreviato | 855
- ALESSIO GATTAFONI-abbreviato | 878
- ELISA IOMMI-abbreviato | 930

E' utile per avere una visione d'insieme di tutto il gruppo.

Lo stesso accade se estraggo SECONDARIA II GRADO - gruppo 2 e non mi estrae

- EMANUELE MARINELLI-abbreviato	1095
- MARGOT MARIA MONELLI-abbreviato	1119
- MARIA VITTORIA PANZAVUOTA-abbreviato	1141
- GIULIA PAOLINI-abbreviato	1143
- IRENE PAPI-abbreviato	1145
- LARA PATRIGNANI-ritirata	1151
- LUCA PONZETTI-abbreviato	1165
- ELISA RITA-abbreviato	1181
- LUCA ROTUNDO-abbreviato	1188
- CAMILLA SABBATINI-abbreviato	1191
- ALICE SACCENTI-abbreviato	1193
- MARTA SALTALAMACCHIA-abbreviato	1194
- LAVINIA SOVERCHIA	1212
- GRAZIA TRAPANI	1224
- IRENE TROTTA	1225
- MICHELA PIETRACCI-solo tirocinio dir_ind	1315
- SONIA VITA	1323

**Comment by francescoKREA** [comment]
Effettuate le correzioni richieste. File progetto aggiornati il 03 dicembre
