### ISSUE TITLE
funzione REPORT, colonna TOTALE ORE EROGATE ATTIVITA'DIDATTICA

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#39]
**ERRORE, PRIORITA’ ALTA**
la colonna TOTALE ORE EROGATE ATTIVITA'DIDATTICA non contiene le ore effettivamente erogate alla data di estrazione ma le ore dell’attività didattica (quelle che dovranno essere erogate a fine corso).
-> la % di frequenza alla data di estrazione è errata

Riporto una schermata dell'estrazione dal 13/09 al 19/10 del gruppo INFANZIA_PRIMARIA
![immagine](https://github.com/user-attachments/assets/faf3ac8b-320d-403d-80ed-d997d8ac20e2)

**Comment by francescoKREA** [comment]
Refuso testo etichetta
