### ISSUE TITLE
Sincronizzazione SW PRESENZE

### ISSUE THREAD

**Issue by ddiamanti-krea** [kreasistemi/KreaEAR#4]
Servirebbe una funzione di sincronizzazione del sw presenze KREASISTEMI con il contenuto di aule.unimc.it da poter utilizzare in autonomia.
Sarebbe utile avere una funzione da cui poter avviare la sincronizzazione DA DATA LEZIONE… A DATA LEZIONE, per CORSO DI STUDIO e per OPERATORE che ha caricato le lezioni, prendendo da aule.unimc.it tutti i dati che rispondono ai parametri inseriti.

Nel corso dell’anno, in aule.unimc.it vengono effettuate delle modifiche (cancellazioni, modifiche di orario, spostamento di aule)… come riportiamo queste modifiche nel sw KREASISTEMI? È possibile impostare un aggiornamento per differenza andando ad aggiornare solo le lezioni che sono effettivamente cambiate oppure che sono state cancellate o che sono state aggiunte.

**Comment by MocavUNIMC** [comment]
RIUNIONE MARIANI / DI GIROLAMO / CAVALLETTI / MERCURI 24/07/2024
La lettura avviene in tempo reale e quindi non c’è una sincronizzazione periodica ma una lettura diretta (facciamo una prova insieme: inserisco una lezione in aule.unimc.it, la cerco nel sw Presenze e la trovo subito, la cancello e non la vedo più -> legge direttamente) 
NON E' NECESSARIA LA SINCRONIZZAZIONE, LA RICHIESTA SI PUO' CHIUDERE
