### ISSUE TITLE
funzione REPORT, ANOMALIA caso Arianna Fiorentino 05/10/2024

### ISSUE THREAD

**Issue by matteomercuri77** [kreasistemi/KreaEAR#40]
Si presenta la seguente anomalia, se filtro per: Secondaria I Grado + 05/10/2024 + "Arianna Fiorentino".

ANOMALIA: 
- Esce un'unica riga con lezione 1 e lezione 2, ma le materie erano diverse da mattina a pomeriggio.
- Se filtro anche per la lezione del pomeriggio ok. Escono le ore di presenza solo per quella materia.
- Se filtro anche per la lezione del mattino, restituisce un record vuoto.

Ho controllato che le associazioni tra aule UNIMC ed il software Presenze sono state fatte in modo preciso.
_POSSIBILE CAUSA DEL PROBLEMA_: in quel giorno è stata inserita manualmente da una tutor una uscita alle 12:30 per dimenticanza della timbratura da parte della Arianna Fiorentino.

**Comment by francescoKREA** [comment]
Ora sono presenti due righe, una per ogni lezione

**Comment by matteomercuri77** [comment]
Il primo punto effettivamente era stato risolto.

Rimane il grande problema che se genero un **export** in foglio di calcolo questo non è coerente con quanto visualizzato a video:
1. le ore di frequenza di frequnza diventano 8.38 a fronte di 3.97 a video
2. la percentuale di presenza a questa attività diventa 41.92 a fronte di 19.85 a video

Come mai?
A regime dovremmo avere un export in excel fedele a quello che vediamo a video oltre che agli orari effettivi importati da hikcentral..

**Comment by francescoKREA** [comment]
Effettuate le correzioni richieste. File progetto aggiornati il 03 dicembre
