### ISSUE TITLE
ANOMALIA REPORT - studente ID 1090 - l'errore influisce su tutti gli studenti

### ISSUE THREAD

**Issue by MocavUNIMC** [kreasistemi/KreaEAR#41]
Prendiamo uno studente della SECONDARIA DI II GRADO – gruppo 1, MARCELLONI GIACOMO – ID 1090
- Se vado in hikcentral nella funzione Attendance Result e imposto il periodo 13/09 – 18/11, vedo che lui ha fatto 120 ore e 45 minuti di presenza.
- se imposto l'estrazione nel report Kreasistemi per questo solo studente mi estra un totale di ore di frequenza molto minore rispetto a quello reale.
- Il calendario della SECONDARIA II GRADO – gruppo 1 è pubblicato al seguente link 
https://sfbct.unimc.it/it/didattica/corso-specializzazione-sostegno/corso-di-specializzazione-per-il-sostegno-a.a.-2023-2024/calendario-didattico 
in due file distinti per settembre/ottobre e novembre/dicembre e le lezioni sono state tutte associate.
Fino ad oggi (21/11/2024) sono state erogate almeno le seguenti lezioni:
-	Didattica speciale: approccio metacognitivo e cooperativo: 30 ore
-	Progettazione del pdf, del pei-progetto di vita e modelli di qualità della vita: dalla programmazione alla valutazione: 30 ore
-	Tirocinio indiretto: 5 ore
-	Didattica speciale e apprendimento per le disabilità sensoriali: 25 ore
-	Didattica delle educazioni e dell'area antropologica: 20 ore
-	Didattica speciale: codici del linguaggio logico e matematico: 10 ore
-	Neuropsichiatria infantile: 10 ore

Su alcune righe viene riportata una % di frequenza superiore al 100%.

**Non stiamo ancora usando il report perché troppo instabile.**

**Comment by francescoKREA** [comment]
Buonasera,
non abbiamo caricato ancora le modifiche perché le stesse hanno portato ad un rilevante rallentamento nelle tempistiche di calcolo, sul quale stiamo lavorando.

**Comment by francescoKREA** [comment]
Effettuate le modifiche al calcolo secondo quanto indicato. File progetto aggiornati il 03 dicembre
