### ISSUE TITLE
ANOMALIA GENERALE REPORT (INUTILIZZABILE)

### ISSUE THREAD

**Issue by matteomercuri77** [kreasistemi/KreaEAR#42]
Ho preso un corsista qualsiasi ad esempio GIUSTINA DI MAURO.

Vi allego un pdf in cui confronto i dati dell'export in excel (prima riga) - della visualizzazione a video (seconda riga) - dei dati grezzi estratti da hikcentral (terza riga).

Mi pare evidente che ci sono INCONGRUENZE che riguardano la differenze nella quantità di tempo di presenza tra una visualizzazione e l'altra; l'impossibilità di associare un orario con un altro perché sono diversi e non ci sono date di riferimento per distinguere le lezioni; la presenza di "assenze" laddove ci sono invece orari registrati...

Inoltre succede anche che cercando per un singolo giorno ed una singola materia per un corsista, escano risultati diversi da qualsiasi altro presente invece in un riepilogo più largo.

In soldoni la mia impressione - ma potrei anche sbagliare - è che sia INUTILIZZABILE questa applicazione (REPORT).
Ma ripeto potrebbe anche dipendere dal fatto che non la so usare io personalmente... e quindi magari potreste spiegarci dove sbagliamo ad utilizzarlo...

Vedere file allegato.
[caso-giustina-dimauro.pdf](https://github.com/user-attachments/files/17846525/caso-giustina-dimauro.pdf)

**Comment by francescoKREA** [comment]
Effettuate le modifiche al calcolo secondo quanto indicato. File progetto aggiornati il 03 dicembre
