### ISSUE TITLE
BLOCCO DEL REPORT SE SETTATA DATA PRIMA DELLA DEFINIZIONE DI UN GRUPPO

### ISSUE THREAD

**Issue by matteomercuri77** [kreasistemi/KreaEAR#44]
Se settiamo una data o un intervallo di date ed a quel punto poi selezioniamo pure uno dei 4 gruppi di corsisti, l'applizazione Report va in blocco mostrando un errore che è riportato nel file allegato.

![FireShot Capture 023 - Errore_ 0 - 193 205 126 12](https://github.com/user-attachments/assets/af15353d-4b08-44cb-b6af-6e704f92e002)

**Comment by francescoKREA** [comment]
Effettuate le correzioni per la risoluzione dell'errore. Applicazione aggiornata il 10 dicembre

**Comment by MocavUNIMC** [comment]
Non si blocca più perché non estrae più nulla
