### ISSUE TITLE
Orario UNIMC

### ISSUE THREAD

**Issue by ddiamanti-krea** [kreasistemi/KreaEAR#7]
Inserendo il filtro per “Creato da” permette di filtrare solo le prenotazioni dell’utente aule.vallebona ma ci interessa filtrare anche altre prenotazioni con diversi parametri che possono essere: OPERATORE, CORSO DI STUDIO, GRUPPO, TIPO LEZIONE…(mi interessano anche le prenotazioni di questo tipo https://aule.unimc.it/view_entry.php?id=606798&area=7&day=21&month=2&year=2024) 
(tutti i filtri devono lavorare con le condizioni concatenate con operatore logico AND)

**Comment by MocavUNIMC** [comment]
Per il momento funziona bene il filtro per operatore, descrizione, data quindi si può chiudere.
Le altre cose le vedremo quando si adatterà il sw ai corsi di studio
